stages:
  - get
  - build

image: alpine

before_script:
  - apk add --no-cache git wget
  - git config --global http.sslVerify false

get_packer:
  stage: get
  tags:
    - bash
  artifacts:
    paths:
    - packer
  script:
    - echo "Fetching packer"
    - wget $packerURL/$packerVersion/packer_"$packerVersion"_linux_amd64.zip
    - unzip packer_"$packerVersion"_linux_amd64.zip
    - chmod +x packer

build_centos-7:
  stage: build
  tags:
    - bash
  script:
    - echo "Deploying CentOS 7"
    - cd centos-7
    - ../packer build -force -var-file variables.json centos-7.json

build_centos-8:
  stage: build
  tags:
    - bash
  script:
    - echo "Deploying CentOS 8"
    - cd centos-8
    - ../packer build -force -var-file variables.json centos-8.json

build_windows-2016:
  stage: build
  tags:
    - bash
  script:
    - echo "Deploying Windows Server 2016"
    - cd windows-2016
    - ../packer build -force -var-file variables.json windows-2016.json

build_windows-2019:
  stage: build
  tags:
    - bash
  script:
    - echo "Deploying Windows Server 2019"
    - cd windows-2019
    - ../packer build -force -var-file variables.json windows-2019.json