stages:
  - get
  - retrieve
  - build

image: alpine

before_script:
  - apk add --no-cache git wget curl jq
  - git config --global http.sslVerify false

get_packer:
  stage: get
  tags:
    - bash
  artifacts:
    paths:
    - packer
  script:
    - echo "Fetching packer"
    - wget $packerURL/$packerVersion/packer_"$packerVersion"_linux_amd64.zip
    - unzip packer_"$packerVersion"_linux_amd64.zip
    - chmod +x packer

retrieve_vault_password:
  stage: retrieve
  tags:
    - bash
  artifacts:
    paths:
    - windows-2019/setup/Autounattend.xml
  script:
    - xmlFile='windows-2019/setup/Autounattend.xml'
    - echo "Retrieving Administrator password from Vault"
    - pass=$(curl -s -H \"X-Vault-Token{{":"}} $VAULT_TOKEN\" -X GET $VAULT_ADDR/v1/credentials/users/misc/administrator | jq '.data.Password' | sed 's/^.//;s/.$//')
    - echo "Updating Autounattend.xml file with Administrator password"
    - sed "s/{{password}}/$pass/g" $xmlFile > $xmlFile

build_centos-8:
  stage: build
  tags:
    - bash
  script:
    - echo "Deploying CentOS 8"
    - cd centos-8
    - ../packer build -force centos-8.json

build_windows-2019:
  stage: build
  tags:
    - bash
  script:
    - echo "Deploying Windows Server 2019"
    - cd windows-2019
    - ../packer build -force windows-2019.json