stages:
  - build
  - deploy

image: alpine

before_script:
  - git config --global http.sslVerify false

get_packer:
  stage: build
  artifacts:
    paths:
    - packer
  script:
    - echo "Fetching packer"
    - wget https://releases.hashicorp.com/packer/1.6.0/packer_1.6.0_linux_amd64.zip
    - unzip packer_1.6.0_linux_amd64.zip
    - chmod +x packer

deploy_windows-2019:
  stage: deploy
  artifacts:
    paths:
    - packerlog.txt
  script:
    - export PACKER_LOG=1
    - PACKER_LOG_PATH="packerlog.txt"
    - echo "Deploying Windows Server 2019"
    - cd windows-2019
    - ../packer build -force -var-file variables.json windows-2019.json
    